apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: Ops Team
  description: The Ops Team organization
  links:
    - url: https://ops.team/
      title: Website
spec:
  type: organization
  profile:
    displayName: Ops Team
    email: info@ops.team
    picture: https://ops.team/assets/img/logo/logo-def3.svg
  children: [infrastructure]
